# Generated by Django 4.2.27 on 2026-01-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spottedmessage',
            options={'verbose_name': 'Spotted Message', 'verbose_name_plural': 'Spotted Messages'},
        ),
        migrations.AlterField(
            model_name='spottedmessage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
