# Generated by Django 4.2.27 on 2026-01-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_spottedmessage_options_alter_spottedmessage_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spottedmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Spotted Message', 'verbose_name_plural': 'Spotted Messages'},
        ),
        migrations.AlterField(
            model_name='spottedmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
