# Generated by Django 4.2.27 on 2026-01-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_spottedmessage_options_alter_spottedmessage_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spottedmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='spottedmessage',
            name='sent_to_n8n',
            field=models.BooleanField(default=False),
        ),
    ]
